const OK_STATUS = 200;
const CREATED_STATUS = 201;
const BAD_REQUEST_STATUS = 400;
const NOT_FOUND_STATUS = 404;

module.exports = {
  BAD_REQUEST_STATUS,
  CREATED_STATUS,
  NOT_FOUND_STATUS,
  OK_STATUS,
};